name: Manual Build

on: workflow_dispatch
jobs:
  manual-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies Install
        run: npm ci
        env:
          CI: true

      - name: Run parser
        run: npm run parse
        env:
          CI: true

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: easylist-for-pi-hole
          path: generated/

      - name: Push generated files into branch
        uses: EndBug/add-and-commit@v5.2.0
        with:
          add: 'generated'
          message: 'Easylist generated files'
          branch: 'generated'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: vsoch/pull-request-action@1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: 'generated'
          PULL_REQUEST_BRANCH: 'master'
