name: Manual Build

on: workflow_dispatch
jobs:
  manual-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies Install
        run: npm ci
        env:
          CI: true

      - name: Create working branch and remove generated files
        run: |
          git branch -D generated || true
          git checkout -b generated
          git rm generated/*
        env:
          CI: true

      - name: Run parser
        run: npm run parse
        env:
          CI: true

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: easylist-for-pi-hole
          path: generated/

      - name: Add new generated files
        run: |
          git add generated/*
          git commit -m 'Easylist generated files'
          git push --set-upstream origin generated --force
        env:
          CI: true

      - name: Open Pull request
        uses: vsoch/pull-request-action@1.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: 'generated'
          PULL_REQUEST_FROM_BRANCH: 'generated'
          PULL_REQUEST_BRANCH: 'master'
