name: Manual Build

on: workflow_dispatch
jobs:
  manual-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies Install
        run: npm ci
        env:
          CI: true

      - name: Run parser
        run: npm run parse
        env:
          CI: true

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: easylist-for-pi-hole
          path: generated/

      ## FIX: https://github.com/github-actions-x/commit/issues/16
      ## https://github.com/rlespinasse/git-commit-data-action
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@1.0.1
      - name: Set git author
        run: git config user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}" && git config user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
      ## /FIX

      - name: Push generated files into branch
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: 'Easylist generated files'
          branch: generated-files
          file_pattern: generated/*
          push_options: '--force'

      - name: Open Pull request
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: vsoch/pull-request-action@1.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "generated-files"
          PULL_REQUEST_FROM_BRANCH: "generated-files"
          PULL_REQUEST_BRANCH: "master"
