name: Parser CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Parse
      run: |
        chmod +x parser.sh
        ./parser.sh
      shell: bash

    - name: Save artifacts
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v2
      with:
        name: easylist-for-pi-hole
        path: output/
